### ISSUE TITLE
Quit normally and not through task manager

### ISSUE THREAD

**Issue by mcrummett** [jcredland/yellow-note#2]
Currently have to kill the task :(

**Comment by jcredland** [comment]
Fixed, now has icons for always on top and close (which fade to dim when the mouse is moved away).
![image](https://cloud.githubusercontent.com/assets/6928506/11929792/f0608178-a7d5-11e5-92d9-185be04695c9.png)
![image](https://cloud.githubusercontent.com/assets/6928506/11929798/021c649a-a7d6-11e5-91f2-dd149e044cb9.png)

**Comment by mcrummett** [comment]
nice!

```
  From: Jim <notifications@github.com>
```

 To: jcredland/yellow-note yellow-note@noreply.github.com 
Cc: mcrummett mark.crummett@btinternet.com
 Sent: Monday, 21 December 2015, 11:29
 Subject: Re: [yellow-note] Quit normally and not through task manager (#2)

Fixed, now has icons for always on top and close (which fade to dim when the mouse is moved away).

**Comment by mcrummett** [comment]
where do i get the new exe? and can nick have it?

```
  From: Jim <notifications@github.com>
```

 To: jcredland/yellow-note yellow-note@noreply.github.com 
Cc: mcrummett mark.crummett@btinternet.com
 Sent: Monday, 21 December 2015, 11:29
 Subject: Re: [yellow-note] Quit normally and not through task manager (#2)

Fixed, now has icons for always on top and close (which fade to dim when the mouse is moved away).

**Comment by jcredland** [comment]
Anyone can have it.   I've GPLd it :)  

I'll need to build a new exe for you - I trashed my Windows Laptop.  Or you can build your own, slightly non-trivial but probably interesting learning experience if you have an hour ...  :) 

Otherwise can build you a new EXE later today!

**Comment by mcrummett** [comment]
sweet
how did you trash it?
wish i had an hour spare atm!

```
  From: Jim <notifications@github.com>
```

 To: jcredland/yellow-note yellow-note@noreply.github.com 
Cc: mcrummett mark.crummett@btinternet.com
 Sent: Monday, 21 December 2015, 11:36
 Subject: Re: [yellow-note] Quit normally and not through task manager (#2)

Anyone can have it. I've GPLd it :) 

I'll need to build a new exe for you - I trashed my Windows Laptop. Or you can build your own, slightly non-trivial but probably interesting learning experience if you have an hour ... :) 

Otherwise can build you a new EXE later today!
