### ISSUE TITLE
Currently always on top

### ISSUE THREAD

**Issue by mcrummett** [jcredland/yellow-note#4]
The app always sits on top which isn't always a good thing

**Comment by jcredland** [comment]
Fixed, now has icons for always on top and close (which fade to dim when the mouse is moved away).
![image](https://cloud.githubusercontent.com/assets/6928506/11929792/f0608178-a7d5-11e5-92d9-185be04695c9.png)
![image](https://cloud.githubusercontent.com/assets/6928506/11929798/021c649a-a7d6-11e5-91f2-dd149e044cb9.png)
